format = """
[](#89b4fa)\
$os\
$username\
[](bg:#cba6f7 fg:#89b4fa)\
$directory\
[](fg:#cba6f7 bg:#313244)\
$git_branch\
$git_status\
[](fg:#313244 bg:#45475a)\
$c\
$rust\
$golang\
$python\
$nodejs\
$lua\
[](fg:#45475a)\
$fill\
$cmd_duration\
$line_break\
$character"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:#89b4fa fg:#11111b"

[os.symbols]
Gentoo = "󰣨 "
Linux = "󰌽 "

[username]
show_always = true
style_user = "bg:#89b4fa fg:#11111b bold"
style_root = "bg:#f38ba8 fg:#11111b bold"
format = "[$user ]($style)"

[directory]
style = "bg:#cba6f7 fg:#11111b bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#313244 fg:#cdd6f4"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#313244 fg:#f9e2af"
format = "[$all_status$ahead_behind ]($style)"

[c]
symbol = ""
style = "bg:#45475a fg:#cdd6f4"
format = "[ $symbol ($version) ]($style)"

[rust]
symbol = "🦀"
style = "bg:#45475a fg:#cdd6f4"
format = "[ $symbol ($version) ]($style)"

[golang]
symbol = ""
style = "bg:#45475a fg:#cdd6f4"
format = "[ $symbol ($version) ]($style)"

[python]
symbol = ""
style = "bg:#45475a fg:#cdd6f4"
format = "[ $symbol ($version) ]($style)"

[nodejs]
symbol = ""
style = "bg:#45475a fg:#cdd6f4"
format = "[ $symbol ($version) ]($style)"

[lua]
symbol = ""
style = "bg:#45475a fg:#cdd6f4"
format = "[ $symbol ($version) ]($style)"

[fill]
symbol = " "

[cmd_duration]
min_time = 2000
format = "[ 󱎫 $duration]($style) "
style = "fg:#a6adc8"

[character]
success_symbol = "[❯](bold #a6e3a1)"
error_symbol = "[❯](bold #f38ba8)"
