monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.pci-0000_00_1b*" }
    ]
    actions = {
      update-props = {
        node.pause-on-idle = false
        session.suspend-timeout-seconds = 0
        api.alsa.headroom = 1024
        api.alsa.period-size = 1024
      }
    }
  }
]
